<template>
  <div class="page-container">
    <h3>About</h3>

      <P>Azure Video Indexer is a cloud and edge video analytics service that uses AI to extract actionable 
      insights from stored videos 1. It is built on Azure Media Services and Azure AI services such as 
      the Face, Translator, Azure AI Vision, and Speech 23. The service enables you to extract insights 
      from your videos using Azure AI Video Indexer video and audio models 2. You can enhance ad insertion, 
      digital asset management, and media libraries by analyzing audio and video content, and improve content 
      discoverability and performance with multichannel analysis, speech transcription, and video editor 1.</P>

      <p>To create a summary of the video transcript, you can use Azure OpenAI Service. 
      It is a cloud-based AI service that provides natural language processing capabilities such 
      as text analysis, language detection, sentiment analysis, and more 4. You can use the service
      to analyze the transcript generated by Azure Video Indexer and extract the most important 
      information from it. For example, you can use the service to summarize the transcript, identify
      key topics, or extract named entities 4.</p>

      <p>By combining Azure Video Indexer and Azure OpenAI Service, you can create a powerful application 
      that can automatically index and summarize your video content. This can be useful for a wide range of 
      applications such as video search, content recommendation, and more.</p>

      <p>To get started with **Azure Video Indexer**, you can visit the official documentation page on 
      Microsoft Learn ³⁴. The page provides a step-by-step guide on how to sign up and upload your first video. 
      
      You can also learn about the different features and scenarios that Video Indexer supports, such as accessibility,
      monetization, content creation, content moderation, and clapperboard support ¹. 
      If you are new to Azure technology, you can check out the **Azure Demo Series** on YouTube. 
      It is a collection of 10 short videos that teach how to get started with Azure ². 
      The videos cover topics such as creating a free account, deploying a web app, and more.</p>

      <p>Source: Conversation with Bing, 12/12/2023
      (1) Understanding Azure Video Indexer. https://www.youtube.com/watch?v=OxTm2jAxm5c.
      (2) Sign up for Azure AI Video Indexer and upload your first video - Azure .... https://learn.microsoft.com/en-us/azure/azure-video-indexer/video-indexer-get-started.
      (3) Azure Video Indexer Intro and Demo. https://www.youtube.com/watch?v=JiKW2YH1LgU.
      (4) Getting Started with Azure Demo Series. https://www.youtube.com/watch?v=iwpY5vCKIvI.
      (5) Home - Microsoft Azure API Management - developer portal. https://api-portal.videoindexer.ai/.
      (6) Azure Video Indexer is now available as an Azure resource. https://techcommunity.microsoft.com/t5/azure-ai-services-blog/azure-video-indexer-is-now-available-as-an-azure-resource/ba-p/2912422.</p>
  </div>
</template>  
<script>
  export default {
    name: 'About',
    data() {
      return {
        
      };
    },
    methods: {
      
    },
  };
</script>  
<style scoped>
</style>